language: java

os: linux

dist: xenial

jdk: openjdk11

services:
  - xvfb

sudo: false
install: true

before_script:
  - echo $HOME
  - pwd
  - ls -la
  - cp src/daResources/maven/settings.xml $HOME/.m2/settings.xml

script:
  - mvn clean deploy

after_success:
  - DA_ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
  - DA_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
  - DA_ARTIFACT_BASENAME="${DA_ARTIFACT_ID}-${DA_VERSION}"
  - DA_DEPLOYMENT_TARGET=$(if [[ $DA_VERSION =~ ^.*SNAPSHOT$ ]]; then echo "snapshots"; else echo "releases"; fi)
  - echo "${DA_ARTIFACT_ID}|${DA_VERSION}|${DA_ARTIFACT_BASENAME}|${DA_DEPLOYMENT_TARGET}"
